# Generated by Django 4.2.7 on 2023-11-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="short_description",
            field=models.CharField(
                default=None, max_length=250, verbose_name="Short description"
            ),
            preserve_default=False,
        ),
    ]
