# Generated by Django 4.2.7 on 2023-11-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0002_restaurant_short_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.FloatField(default=5, verbose_name="Rating"),
            preserve_default=False,
        ),
    ]
