# Generated by Django 4.2.7 on 2023-11-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0003_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="short_review",
            field=models.CharField(
                default="Mid", max_length=250, verbose_name="Short review"
            ),
            preserve_default=False,
        ),
    ]
