# Generated by Django 4.2.7 on 2023-11-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0004_review_short_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="logo",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="restaurant/",
                verbose_name="Restaurant Image",
            ),
        ),
    ]
